### ISSUE TITLE
dc motor can not running

### ISSUE THREAD

**Issue by ahmedgamal22** [parikshitpagare/3-mode-bluetooth-robot#1]
dc motor can not running i connect circuit as digram but dc motor do not work servo motor work but cannot move robot

**Comment by parikshitpagare** [comment]
The motor driver used in the project accepts inverted PWM (0 means 255 and vice-versa). Please make changes accordingly in the code. This is mentioned in the code as well.

**Comment by parikshitpagare** [comment]
> dc motor can not running i connect circuit as digram but dc motor do not work servo motor work but cannot move robot

**Comment by iaananth** [comment]
same issue - 
one side only dc motor running, servo motor and ultrasonic sensor working....

@parikshitpagare @ahmedgamal22 

what changes in code?
